### ISSUE TITLE
Still have issue with 'max props'....

### ISSUE THREAD

**Issue by mistahwolf** [itsjustcurtis/MenyooSP#101]
Tried numerous times to get answers over on the old 'Menyoo' Github. Maybe now someone over here knows something. Ever since the (spits) 'Contract' dlc, with each update, the max number of props I could use in a build kept shrinking. Before the contract, the max was '1996' which was more than enough for a large build. As of the 'Drug Wars' (I haven't bothered to update and my game is the most stable it's ever been) I'm down to around '650'. 

Anything that goes over the latest number crashes the game and I can't access the build to fix anything. I can 'convert' to ymap with 'Menyoo 2 ymap converter', but can't change anything (like make doors 'dynamic'.) Still learning how to convert to ymap with Codewalker but that's far more complicated. I've raised the 'Object Pool' size with no luck. One possible 'cause' might be with 'Map Builder Props' as I've opened large scenarios that didn't have any MBP's without problems, but couldn't add anything or menyoo will crash.

Anybody got any ideas or is having a similar issue?

**Comment by itsjustcurtis** [comment]
Given that this issue appears to worsen with each new update, this tells me that this is not an issue with Menyoo, and simply the game running out of memory as more and more content gets added.

**Comment by mistahwolf** [comment]
Like you I thought this was a 'Memory Issue' as well. Yet, it seems more
like a 'Map Builder' issue as I see lots of large builds from others using
both. I've checked old builds that have few or no MB props and have loaded
in over '900+' props and peds. I've used the latest MB updates and my
'small builds' load fine, just not the large ones and Menyoo doesn't seem
able to handle them. I'm fuggin' stumped. Thanks for getting back though.
BTW, any headway figuring out the 'marker teleports' issue?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
