### ISSUE TITLE
"Added" missing blips to GTAblip.h and .cpp, can you test it?

### ISSUE THREAD

**Issue by ThatRealSpicyDragon** [itsjustcurtis/MenyooSP#103]
[MenyooBlips.zip](https://github.com/user-attachments/files/15839177/MenyooBlips.zip)

### I just want to make it clear; I'm not a modder.

I have no idea if this was done correctly. I don't know how to compile the zip, so I have no way of knowing if it worked. But I copied the format that was in the two GTAblip files.
The ZIP file is based on the most recent pre-release, but I also isolated both GTAblip files as copies.
This was extremely tedious to do and took two days, so I would appreciate if you could check it out. Thanks.

**Comment by itsjustcurtis** [comment]
This is not an issue with Menyoo. Please ask for support like this on the discord server where other players can help.
