### ISSUE TITLE
Bottom Dollar Bounties (mp2024_01) - INFO

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [itsjustcurtis/MenyooSP#107]
This should help 😎

**Comment by Mathu-lmn** [comment]
Game build Version

Number : 3258
Aliases : mp2024_01
Name : Bottom Dollar Bounties
Release date : 25/06/2024


Vehicles:
- Castigator
- Coquette5 (Coquette D1)
- Dominator10
- Driftcypher (Cypher Drift Mode)
- Driftnebula (Nebula Turbo Drift Mode)
- Driftsentinel (Sentinel Classic WideBody Drift Mode)
- Driftvorschlag
- Envisage
- Eurosx32
- Niobe
- Paragon3 (Paragon S)
- Pipistrello
- Pizzaboy
- Poldominator10
- Poldorado (Dorado Cruiser)
- Polgreenwood (Greenwood Cruiser)
- Policet3
- Polimpaler5 (Impaler SZ Cruiser)
- Polimpaler6
- Vorschlaghammer
- Yosemite1500

Weapons:
- WEAPON_STUNROD (New weapon)
- w_pi_stungun_m41 (New Skin for the StunGun)


Peds:
- csb_jenettee
- csb_maude_02
- g_m_m_zombie_01
- g_m_m_zombie_02
- g_m_m_zombie_03
- ig_bountytarget_01
- ig_bountytarget_02
- ig_bountytarget_03
- ig_bountytarget_04
- ig_bountytarget_05
- ig_bountytarget_06
- ig_jenettee
- ig_maudebf
- ig_mechanic_03
- s_m_m_bailoffice_01

Interiors/Business:
- m24_1_dlc_int_bounty (New MLO) 
- m24_1_int_placement_m24_1_interior_dlc_int_bounty_milo_ (Position XYZ: 565.887 -2688.762 -50)
- m24_1_bailoffice_davis (External Decorations) (Position XYZ: 123.25 -1708.43 29.13)
- m24_1_bailoffice_delperro (External Decorations) (Position XYZ: -1415.52 -654.33 28.55)
- m24_1_bailoffice_missionrow (External Decorations) (Position XYZ: 485.75 -945 27.24)
- m24_1_bailoffice_paletobay (External Decorations) (Position XYZ: -62.74 6500.37 31.47)
- m24_1_bailoffice_vinewood (External Decorations) (Position XYZ: 77.69 21.22 69.19)

IPLS/Maps:
- m24_1_carrier (New Aircraft Carrier) (Position XYZ: -3259.89 3909.33 26.78)
- m24_1_carrier_int1
- m24_1_carrier_int2
- m24_1_carrier_int3
- m24_1_carrier_int4
- m24_1_carrier_int5
- m24_1_carrier_int6
- m24_1_carrier_ladders
- m24_1_legacyfixes
- m24_1_pizzasigns

New Gen Exclusive Interior:
- m24_1_dlc_int_mod (The Vinewood Club Garage Workshop)
- m24_1_int_placement_m24_1_g9ec_interior_0_dlc_int_mod_milo_ 
(Position XYZ: 649.7397 -2688.76172 -50)

New props list : [mp2024_01props list - Pastebin.com](https://pastebin.com/TtMtKXWz)

New cutscenes : 
- sum24_btw_arralive_mcs5
- sum24_btw_arrdead_mcs1
- sum24_btw_cell_ext
- sum24_btw_dead_ext
- sum24_bty3_ko_mcs2
- sum24_bty4_heavy_mcs3
- sum24_bty6_escape_mcs4
- sum24_office_int

New animations : https://pastebin.com/85AG3yty

**Comment by TayMcKenzieNZ** [comment]
The dump was also updated

https://github.com/DurtyFree/gta-v-data-dumps

**Comment by TayMcKenzieNZ** [comment]
Can you please update the ASI to support the latest gamebuild, 3258 @itsjustcurtis?

**Comment by TayMcKenzieNZ** [comment]
Thank you 😊
