### ISSUE TITLE
Custom Added YCD Animations Bug/Crashes

### ISSUE THREAD

**Issue by Quechus13** [itsjustcurtis/MenyooSP#119]
When using Menyoo to play custom animations in GTA 5, I've encountered a significant bug that disrupts the seamless transition between animations. While Menyoo is capable of playing individual custom animations without issue, switching from one custom animation to another causes severe glitches in the character's movements.

Issue Details

Initial Animation Playback:

Each custom animation plays correctly when initiated. The character performs the actions as intended, without any noticeable issues.

Transitioning Between Animations:

When switching from one custom animation to another, the character's arms often become misaligned or move into unnatural positions. This results in the character appearing distorted, with limbs in incorrect orientations.

Severe Glitches:

In some instances, attempting to play a new custom animation after an initial one can lead to severe graphical glitches. These glitches manifest as characters' limbs twisting or bending in ways that are not physically possible, breaking the immersion and visual coherence of the game.

Game Stability Issues:

Repeatedly switching between different custom animations not only distorts the character's movements but can also lead to game instability. In some cases, this instability results in the game crashing entirely, forcing a restart.

**Comment by itsjustcurtis** [comment]
Unfortunately this is out of the scope of what Menyoo can do. All it can do is call the animations to play, it has no control over how the game interprets that animation or how the transitions should look, that is down to the animation itself.
The game itself has hundreds, if not thousands of intermediate "in" and "out" animations paired with all of its main animations; if those have not been created and/or used as part of a larger sequence then its not surprising that the animation glitches and causes odd behaviour
