### ISSUE TITLE
Chameleon paints show in Menyoo Customs when no Chameleon mods are installed

### ISSUE THREAD

**Issue by itsjustcurtis** [itsjustcurtis/MenyooSP#12]
Paint option was added to allow players to easily access the new Chameleon paint options, however without the mods installed, users are presented with solid black colours and varying pearlescents.

**Comment by itsjustcurtis** [comment]
I don't believe there is a way to fully protect against this, perhaps a warning similar to the wheel paint options would be suitable here?

**Comment by Wildbrick142** [comment]
>  don't believe there is a way to fully protect against this

putting the menu option(s) behind a `IS_DLC_PRESENT(GET_HASH_KEY("spchameleon"))` check should get the job done, since both mods are dependent on that pack being active in game

**Comment by itsjustcurtis** [comment]
Ooh that is an interesting observation,  definitely worth considering,
thanks
