### ISSUE TITLE
Vehicle speed mismatch when spawning a new vehicle

### ISSUE THREAD

**Issue by itsjustcurtis** [itsjustcurtis/MenyooSP#14]
When spawning a vehicle at speed, the vehicles velocity is maintained, but speed is not, and thus the vehicle slows down before users are able to accelerate again

**Comment by metoxys** [comment]
Need to be careful with testing whatever change is made to address this so it won't mess with the behavior of the vehicle

**Comment by itsjustcurtis** [comment]
Yeah, from what I understand there is a specific property called vehicle
speed, that accounts for gearing, wheel speed and some other things; if
entity velocity doesn't match then the game does what we currently
experience. Some investigation required on a new branch.
