### ISSUE TITLE
Teleport crashing

### ISSUE THREAD

**Issue by ropp11** [itsjustcurtis/MenyooSP#154]
Teleporting to interiors crashes. How to fix?

**Comment by itsjustcurtis** [comment]
Can you provide more detail please? Is it specific interiors that are causing crashes, have you tested with all other mods deactivated, is it with protagonist peds or other peds?

**Comment by itsjustcurtis** [comment]
I'm unable to replicate the issue. If you can provide more detail then I may be able to reopen.

**Comment by ropp11** [comment]
I have the 5 basic mods installed: Menyoo 2.0, ScriptHookV 1.0.3274, ScriptHookVDot, Ovisetup, NativeUI.

It's almost every interior, except the 2 Banks. Every Apartment, Customisable and office interiors.

Installed Game: GTA 5 – v1.0.3095/1.68 + NVE Platinum Modpack

**Comment by itsjustcurtis** [comment]
First thing I immediately notice is you're running a severely out-dated version of the game. I am also aware of issues with NVE conflicting with other mods. I would suggest both updating your game first, then trying to deactivate NVE; As I say I am unable to replicate this issue at all, I have teleported to all interiors in turn and see no issues.

**Comment by ropp11** [comment]
Thx. How do I deactivate NVE? Just deleting all the "NVE..." files in dlcpacks?

**Comment by TayMcKenzieNZ** [comment]
I believe the same pack you used to install, has an uninstaller. You would
need to find and troubleshoot this yourself, possibly via YouTube.

**Comment by ropp11** [comment]
Thx it works now. I made a backup file and deleted all the "NVE" related files from dlcpacks.

**Comment by itsjustcurtis** [comment]
Glad to hear, if you are the one that left the 1.5 star 5-mods review for teleports, would you kindly remove it
