### ISSUE TITLE
Missing weathers

### ISSUE THREAD

**Issue by crxhvrd** [itsjustcurtis/MenyooSP#155]
Currently in Menyoo there are some missing weathers that can't be enabled:
Xmas
Snow Halloween (Added in the new update)
Rain Halloween (Added in the new update)
Hope they will be added soon

**Comment by vbelevcev** [comment]
\Solution\source\Scripting\enums.h
{
	Unknown = -1,
	ExtraSunny,
	Clear,
	Clouds,
	Smog,
	Foggy,
	Overcast,
	Rain,
	Thunder,
	Clearing,
	Neutral,
	Snow,
	Blizzard,
	SnowLight,
	Xmas,
	Halloween,
	SNOW_HALLOWEEN,
	RAIN_HALLOWEEN"
};

\Solution\source\Scripting\World.cpp
namespace World
{
	const std::vector<std::string> World::sWeatherNames{
		"ExtraSunny",
		"Clear",
		"Clouds",
		"Smog",
		"Foggy",
		"Overcast",
		"Rain",
		"Thunder",
		"Clearing",
		"Neutral",
		"Snow",
		"Blizzard",
		"SnowLight",
		"XMAS",
		"Halloween",
		"SNOW_HALLOWEEN",
		"RAIN_HALLOWEEN"
	};

**Comment by itsjustcurtis** [comment]
> \Solution\source\Scripting\enums.h { Unknown = -1, ExtraSunny, Clear, Clouds, Smog, Foggy, Overcast, Rain, Thunder, Clearing, Neutral, Snow, Blizzard, SnowLight, Xmas, Halloween, SNOW_HALLOWEEN, RAIN_HALLOWEEN" };
> 
> \Solution\source\Scripting\World.cpp namespace World { const std::vectorstd::string World::sWeatherNames{ "ExtraSunny", "Clear", "Clouds", "Smog", "Foggy", "Overcast", "Rain", "Thunder", "Clearing", "Neutral", "Snow", "Blizzard", "SnowLight", "XMAS", "Halloween", "SNOW_HALLOWEEN", "RAIN_HALLOWEEN" };

Thanks for this, saves me a lot of effort! If you want to create a fork and PR into Menyoo, the change will be properly attributed to you, otherwise I'll add these in and ensure your name is mentioned in the commit.

**Comment by itsjustcurtis** [comment]
I've just had a go at this, but none of the 3 new names are responsive in game. I'll need to do some more digging to figure out whats missing

**Comment by vbelevcev** [comment]
¯\_(ツ)_/¯
![image](https://github.com/user-attachments/assets/bee23351-1968-4f9a-a71a-c542b9fd863d)
![image](https://github.com/user-attachments/assets/0f4094fe-df4c-4673-a4ed-40f8516263a5)
maybe I didn't change anything in enum

**Comment by itsjustcurtis** [comment]
Yeah I'd fucked up a typo, entirely on my that one.

I managed to get the Halloween ones working now, Xmas for some reason is glitching on me; appears for a second then defaults to extra sunn, do you get the same?

**Comment by itsjustcurtis** [comment]
Xmas weather refusing to play ball for some reason. Was always included in Menyoo but was commented out, leading me to believe this is a long-standing issue. Closing as resolved for the addition of the two new weathers
