### ISSUE TITLE
Vehicle previews out-dated

### ISSUE THREAD

**Issue by itsjustcurtis** [itsjustcurtis/MenyooSP#16]
Many vanilla vehicles are missing their previews. Need to understand how this code works and update.

**Comment by itsjustcurtis** [comment]
Looks like this relies on the vVehicleBmps array which is pre-populated with hardcoded texture dictionary names and vehicle ids, then appended with any user images in the Vehicle Previews folder.

Easy win is to append the missing textures from the game files in here, though I would rather a dynamic selection that somehow uses whatever the game uses to generate those images on the websites.

**Comment by TayMcKenzieNZ** [comment]
You can simply use this:

https://www.gta5-mods.com/misc/vehicle-previews-all-vehicles

**Comment by itsjustcurtis** [comment]
I want to try and keep the previews folder clean for users to add their own; where possible, all vanilla content should be ready to go within menyoo

**Comment by itsjustcurtis** [comment]
Consolidated to #27
