### ISSUE TITLE
Search for clothes by ID. 

### ISSUE THREAD

**Issue by bigsmileling** [itsjustcurtis/MenyooSP#164]
As I explained on Discord, adding an option for each category (torso, tops, emblems, shoes, etc.) to go to a specific ID, similar to Discord's search feature that allows you to jump to a specific page by entering the number.

For example, I have 4000 jbibs (shirts), and I want to go to ID 2349, so it would just be using that option in the jbibs (shirts) category.
![image](https://github.com/user-attachments/assets/c425dbcf-ac94-4640-ac85-3936154841d1)

**Comment by itsjustcurtis** [comment]
This should be a relatively easy fix, just add an inputbox to the AddNumber function against the clothing id selection.
