### ISSUE TITLE
motorcycle rims crashing menyoo

### ISSUE THREAD

**Issue by Senox343** [itsjustcurtis/MenyooSP#165]
Hey, I wanted to report a bug I encountered with motorcycles in the game. Whenever I try to change the rims on any motorcycle, it causes Menyoo to crash. After the crash, the wheel change applies, but Menyoo stops working entirely. Could you please look into this issue?
Thanks!

**Comment by itsjustcurtis** [comment]
Is this on _all_ bikes or only on specific ones? If its only on specific ones can you check with all other mods disabled?

**Comment by Senox343** [comment]
So, I checked and it turned out that the issue was likely caused by a mod in the mods folder conflicting with Menyoo. I apologize for the inconvenience, and thank you for providing Menyoo.

**Comment by itsjustcurtis** [comment]
Thanks for confirming
