### ISSUE TITLE
Suggestions To Enhance The Menu

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [itsjustcurtis/MenyooSP#17]
Hey man, first of all I want to say great work!

Menyoo can work in FiveM however the ASI file needs to be updated every time there's an update. The way we've been able to accomplish this is by "hacking" the ASI file:

# FiveM Support

Step 0: Install Visual Studio and download [Resource Hacker](https://www.angusj.com/resourcehacker/)
Step 1: Make a dummy.txt file.
Step 2: Make a fx_asi_build.rc file.
Step 3: Copy the following into said rc file with notepad or whatever.

```
FX_ASI_BUILD 2802 dummy.txt
FX_ASI_BUILD 2189 dummy.txt
FX_ASI_BUILD 2372 dummy.txt
FX_ASI_BUILD 2545 dummy.txt
FX_ASI_BUILD 2612 dummy.txt
FX_ASI_BUILD 2628 dummy.txt
FX_ASI_BUILD 2699 dummy.txt
FX_ASI_BUILD 2944 dummy.txt
FX_ASI_BUILD 3095 dummy.txt
```

Step 4: Open the rc file with Visual Studio and save as res.

Step 5: Run Resource Hacker, then go to File>Open, select all files and choose your .ASI file

Step 6: Navigate over to Action >Add from Resource File and select your newly created .res file

Step 7:Click on check all and import

Step 8:Save and Enjoy.

# Content For Future Updates

Getting the required content to update the menu can be a pain in the ass, however thanks to a good friend of mine, DurtyFree, you can easily find important content such as vehicle names, ped names, IPLs, etc etc on his GitHub here:

https://github.com/DurtyFree/gta-v-data-dumps

# Suggested features

- Update the list of [particle effects](https://github.com/DurtyFree/gta-v-data-dumps/blob/master/particleEffectsCompact.json)
- Update the list of [animations](https://github.com/DurtyFree/gta-v-data-dumps/blob/master/animDictsCompact.json)
- Add an option to anchor boats and sea plane
- Update tattoos
- Update badges and shirt overlays
- Update facial overlays

I hope the links and suggestions are helpful 😃 for the longest time I was updating easy things like vehicles and peds and the [Object List](https://github.com/DurtyFree/gta-v-data-dumps/blob/master/ObjectList.ini) but I don't know anything about C++ to properly update and maintain the menu.

Good luck and love what you're doing 👍

**Comment by itsjustcurtis** [comment]
Thanks for the suggestsions. Aware of Durtyfrees repo (you might see I have an old fork of it on my profile! And will slowly migrate the latest stuff into future patches of menyoo. 

The fivem updates require minimal effort to be honest, I would rather stick to that manually than relying on third party software, but may consider it if it becomes more arduous in future.

**Comment by TayMcKenzieNZ** [comment]
Yeah, MAFINS never bothered so we would just do it this way lol. Might as well do it properly though.

**Comment by itsjustcurtis** [comment]
Tay, I'm gonna close this issue for now following the convo I had with durty about attempting to api in to his repo. All suggestions beyond anchoring are simply a case of updating the txt files which anyone can do.

**Comment by TayMcKenzieNZ** [comment]
Nice, no problem 😀.
