### ISSUE TITLE
More Custom Online Interiors

### ISSUE THREAD

**Issue by ontickjayden** [itsjustcurtis/MenyooSP#177]
Hello, can there be a customizable Agency and Casino Penthouse interior?

**Comment by TayMcKenzieNZ** [comment]
You can use Simple Trainer. Menyoo doesn't load ipls and entitysets.

**Comment by ontickjayden** [comment]
> You can use Simple Trainer. Menyoo doesn't load ipls and entitysets.

Hi, I checked simple trainer and I don't see an Agency teleport option, or did I just not notice it?

**Comment by mistahwolf** [comment]
@ontickjayden, depending on your game version and the vers. of 'Simple Trainer', if what you're looking for has been added it will be in the 'Teleports -> Other Teleports' menu. Scroll down the available DLC list (example; Vinewood or Heist 3) and find the one where Agency teleports would be. If you can't find them, you'll need to update your game and or wait til' ST gets updated.

**Comment by ontickjayden** [comment]
> @ontickjayden, depending on your game version and the vers. of 'Simple Trainer', if what you're looking for has been added it will be in the 'Teleports -> Other Teleports' menu. Scroll down the available DLC list (example; Vinewood or Heist 3) and find the one where Agency teleports would be. If you can't find them, you'll need to update your game and or wait til' ST gets updated.

Hi, I found the agency and casino interiors, thanks

**Comment by itsjustcurtis** [comment]
I assume this is safe to be closed based on the above conversation
