### ISSUE TITLE
Car model name information in Menyoo 2

### ISSUE THREAD

**Issue by Listiqq** [itsjustcurtis/MenyooSP#18]
Hi! 
1. Very need to add ability to see which car model spawn (yft/ytd name). Very very useful !
This feature will allow to adjust the car’s handling using the real time handling editor and immediately write it to a handling file. Otherwise it is impossible to remember the name of the handling name.
2. Also, will be very cool categorize DLC vehicle by dlc name and ability categorize by vendor.
3. Last suggestion - add hotkeys assigment.
Thank you for your work man !!!

**Comment by itsjustcurtis** [comment]
1) I like the spawn name idea, I'll have a look into the cleanest way to implement it without making the menu system too busy.
2) This may involve more hard-coding than I would like. I _may_ implement a method where users can create their own categories (using the vehicles.xml file) with a dlc default added to it
3) Hotkeys I'm not too keen on adding; it irritates me no end when I accidentally hit a hotkey from one of the other trainers, and it leaves wayy to much room for conflict.

**Comment by Listiqq** [comment]
1. "I like the spawn name idea, I'll have a look into the cleanest way to implement it without making the menu system too busy."
For example - it could be under the preview icon, on the side of the main menu. If preview icon is not installed - then just on the side opposite the car selected in the menu. Anyway - I'm waiting for it impatiently.

2. "I may implement a method where users can create their own categories (using the vehicles.xml file) with a dlc default added to it" 
It will be very very cool ! We can arrange our addon cars however we want! For example - I would arrange them by car manufacturer in the order I would like and not just alphabetically! I will really look forward to this opportunity! As for the DLC, it’s just convenient - to know which DLC car was presented in which DLC Pack

3. Personally, I have enough of the capabilities that I have now, but perhaps someone people would like to reassign the keys for resetting the wanted level, teleport, or repair a car. Anyway - it's at your discretion

4. I completely forgot about one more feature ! It would be great to add "Enable MP Maps" button and add Cayo Perico Island to the teleport list. I would then completely refuse to use ST ;)

**Comment by itsjustcurtis** [comment]
closed with PR #144
