### ISSUE TITLE
9th Gen content detected

### ISSUE THREAD

**Issue by ehjr5u** [itsjustcurtis/MenyooSP#187]
![20240922084046_1](https://github.com/user-attachments/assets/76245f5e-00ce-4b8e-8ccd-a4d3e2a66ebf)

So I just installed Menyoo 2.0 and I notice a warning that shows that I have 9th Gen content. I check the log file and i notice this:

![image](https://github.com/user-attachments/assets/b1fdf1f5-db01-4b82-a900-ca331277c450)

Yeah I don't know what to do and I notice that the game lag spikes and crashes often even when navigating the menu, it doesn't happen to Menyoo 1.0

**Comment by itsjustcurtis** [comment]
This is a feature, not an issue. Follow the instructions provided at the end of the log file.

**Comment by ehjr5u** [comment]
I don't understand how to remove the dlcs, search that .xml that the log told me to remove lines in Openiv and I don't see it. Is it somewhere else? And will it affect the game I want to play Online?

**Comment by ehjr5u** [comment]
Is there anything else I recommend deleting excluding the example from the log?
