### ISSUE TITLE
When installed to FiveM. open keybind may not be able to be changed.

### ISSUE THREAD

**Issue by vaktsn** [itsjustcurtis/MenyooSP#188]
Even if changed in the menyooconfig file the opening keybind will continue to be f8

**Comment by TayMcKenzieNZ** [comment]
Not true. I was able to change to ~ with no issue.

**Comment by itsjustcurtis** [comment]
Yeah the keybind can definitely be changed for fivem. Please check your configuration in both your SP and Fivem Install.
