### ISSUE TITLE
Disable 'F9' Spooner toggle....

### ISSUE THREAD

**Issue by mistahwolf** [itsjustcurtis/MenyooSP#200]
Using 'Spooner's F9 toggle' is a left over from when spooner was separate from Menyoo. It is no longer necessary and it takes up a perfectly good spot mod creators can use. I have a fuel script that also uses F9 and it's a PIA to do the 'toggle shuffle' getting Spooner out of the way. We can easily access Spooner through Menyoo. It's time for that option to go....

**Comment by blancodagoat** [comment]
It is needed. Just rebind the key.

**Comment by itsjustcurtis** [comment]
I see a lot of people still using the F9 key for spooner. For this specific use-case then the key can be bound to a different key or null to free up the F9 key.

**Comment by mistahwolf** [comment]
I use Spooner a lot. It's simple to activate when you use F8 to get into
the Menyoo 'menu'. It doesn't make sense to have two separate toggles when
they're bound together. There's only so many keys to 'rebind' and modders
make their stuff like they live in a vacuum and no one else will think of
using the same keys as they do. Better to just turn it off.
