### ISSUE TITLE
ASI plugin not updated, thus Menyoo doesn't work after update 

### ISSUE THREAD

**Issue by Longjohnathan** [itsjustcurtis/MenyooSP#208]
Title speaks for itself. I've installed everything correctly, and have never had this happen in the plus year I've used Menyoo 1/2.0, so I know I'm not doing anything 'wrong.'

**Comment by gue88** [comment]
SCRIPTHOOKV NEEDS TO BE UPDATED

**Comment by Longjohnathan** [comment]
It was already updated?

**Comment by Longjohnathan** [comment]
And I also know that because I've installed the new version of Scripthook
and can launch the game just fine without a fatal error

**Comment by gue88** [comment]
Not the 12th December update, GTA updated again

**Comment by Longjohnathan** [comment]
But if this was the case the game wouldn't launch without that fatal script
hook error, plus I'd have had to install a new update?

**Comment by gue88** [comment]
Gotta wait

**Comment by Longjohnathan** [comment]
"installed content update Dec 13,"alright if that's the case though, this
problem was the same as yesterday, and for some reason it still launches
with scripthook so that has to be up to date?

**Comment by itsjustcurtis** [comment]
Not a menyoo issue. The game was updated a second time 13th December and scripthook is yet to be updated. Please use the discord server for specific support.
