### ISSUE TITLE
Bermuda Triangle LSPDFR Bug

### ISSUE THREAD

**Issue by itsjustcurtis** [itsjustcurtis/MenyooSP#21]
![image](https://github.com/itsjustcurtis/MenyooSP/assets/70447190/bd8a9e53-c291-4f8f-819a-af02b3c2730c)

**Comment by itsjustcurtis** [comment]
Fixing bugs and incompatibilities with other mods is outside the scope at the moment. If it is to be looked into, significantly more information is required.

**Comment by WithLithum** [comment]
@itsjustcurtis Additional information pursuant to another mod author "Bejoijo" (i dunno it is the correct name): The Bermuda Triangle bug is where LSPDFR could unable to spawn entities and callouts through some areas of the world with no reasonable explaination with no possible fix other than reinstalling the game until it works.
