### ISSUE TITLE
game already running

### ISSUE THREAD

**Issue by MrNiico21** [itsjustcurtis/MenyooSP#210]
i only have menyoo + the needed files and an updated version of scripthook v and battleeye disable and since the latest update, the launcher is telling me the game is already running. without menyoo, the game run perfectly
![Untitled](https://github.com/user-attachments/assets/32b569df-9f50-477c-b523-29582c79ed38)

**Comment by itsjustcurtis** [comment]
Have you tried other trainers to confirm this is isolated to menyoo and is not a wider scripthook issue? Especially given that scripthook has not yet updated following the additional game update on Friday.

**Comment by MrNiico21** [comment]
yes, ive tried one other and there was no issue, only with menyoo

**Comment by itsjustcurtis** [comment]
What other trainer did you try? And this is today, following the update?

**Comment by MrNiico21** [comment]
Simple Trainer and it was yesterday

**Comment by itsjustcurtis** [comment]
Please reinstall simple trainer and try to launch now, send screenshots to confirm that it works in game.

**Comment by MrNiico21** [comment]
after verification, the game still does the same thing which means it is not specific to menyoo
