### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Fen1ksov** [itsjustcurtis/MenyooSP#216]
Game crashes due to MP Freemode Ped Female on Tops 626 from DLC mp2024_02

**Comment by itsjustcurtis** [comment]
Do you get the warning about Gen9 content detected when launching?

**Comment by Fen1ksov** [comment]
> Do you get the warning about Gen9 content detected when launching?

I misunderstood the question a bit, but there were no warnings, just an instant crash out of the game.

**Comment by itsjustcurtis** [comment]
When you first open Menyoo, did a warning pop up at the bottom of the screen saying "Gen 9 content detected"

**Comment by Fen1ksov** [comment]
> When you first open Menyoo, did a warning pop up at the bottom of the screen saying "Gen 9 content detected"

Yes - https://i.imgur.com/1zoBfu8.png

**Comment by itsjustcurtis** [comment]
Then you need to follow the instructions in the log. This is not a menyoo issue, but a game issue of trying to load null gen9 data.
