### ISSUE TITLE
FiveM Crash

### ISSUE THREAD

**Issue by MixJesteR** [itsjustcurtis/MenyooSP#24]
Game it crashes at "Starting Up"

**Comment by MixJesteR** [comment]
BUILD: 2802

**Comment by TayMcKenzieNZ** [comment]
It shouldn't do 🤔 I checked the ASI file and it should support all
gamebuilds however if for some odd reason it's not, you'll have to "hack
it". See here for how:

https://forum.cfx.re/t/how-to-make-a-res-file-and-update-your-asi-files/5090038

**Comment by itsjustcurtis** [comment]
The [ReadMe](https://github.com/itsjustcurtis/MenyooSP/blob/main/README.md) file specifies b3095 as the required game build. There are natives in Menyoo pertaining to Gen9 protection and snow coverage that do not exist in older versions.

**Comment by itsjustcurtis** [comment]
There may be a method to allow older versions of the game to still function. Re-opening with "workaround applied" to track.

**Comment by itsjustcurtis** [comment]
Confirmed issue originated in rc build, likely caused by newly introduced memory interrogation to bypass the need for hardcoded memory edits.

**Comment by itsjustcurtis** [comment]
@MixJesteR please download the [Latest Pre-release](https://github.com/itsjustcurtis/MenyooSP/releases/download/v2.0.1a1/MenyooSP.zip) and advise if this works with your version of FiveM

**Comment by TayMcKenzieNZ** [comment]
I downloaded the latest pre release however it crashes when you access player options in fivem.

**Comment by itsjustcurtis** [comment]
> I downloaded the latest pre release however it crashes when you access player options in fivem.

Are you also using an older fivem build? I asked mix to test specifically because they are using a much older version. 

Please raise the player option crash as a separate issue.

**Comment by TayMcKenzieNZ** [comment]
Using latest build. It crashes due to the gen9 content. replacing them with Alex106's files fixed it.

**Comment by MixJesteR** [comment]
Still crashes with the new gamebuild. All mods updated.
I use Lambda, TrainerV, opencamera... more, but isn't a problem I suppose.

**Comment by MixJesteR** [comment]
> Using latest build. It crashes due to the gen9 content. replacing them with Alex106's files fixed it.

Can you help me?

**Comment by TayMcKenzieNZ** [comment]
> Can you help me?

Take a look here. You need to update Lambda, TrainerV, opencamera etc using this tutorial

https://forum.cfx.re/t/how-to-make-a-res-file-and-update-your-asi-files/5090038

That's all the help I can supply as I will not be doing it for you. Watch the videos and read the tutorial. Translate it if you need to. Good luck.

**Comment by MixJesteR** [comment]
> > Can you help me?
> 
> Take a look here. You need to update Lambda, TrainerV, opencamera etc using this tutorial
> 
> https://forum.cfx.re/t/how-to-make-a-res-file-and-update-your-asi-files/5090038
> 
> That's all the help I can supply as I will not be doing it for you. Watch the videos and read the tutorial. Translate it if you need to. Good luck.

Man I've the everything updated. Problem is this Menyoo.Asi crashes the game.

**Comment by TayMcKenzieNZ** [comment]
Stop your server and delete your server cache, use the latest recommended server artificacts. I was having issues with it but then after I deleted the server and client cache, everything was fine. 

I do think though that some gen9 stuff is causing Menyoo to poop itself which is why I was having issues with the player appearance menu earlier. I have since downloaded that mp-stub-clothes-patch thing from Alex106 over at GTA5Mods, added prefixes to all the file names to replace the original ones and streamed it as a resource.

I'm not sure if possible but perhaps Menyoo, vMenu, etc etc needs to ignore those files or perhaps servers need to stream them, same with the chameleon paints for it to take effect, though I'm not 100% certain.

*You'd have to rename the files yourself using Bulk Rename Utility (google it) if you wanted to do this)*

**Comment by MixJesteR** [comment]
> Stop your server and delete your server cache, use the latest recommended server artificacts. I was having issues with it but then after I deleted the server and client cache, everything was fine.
> 
> I do think though that some gen9 stuff is causing Menyoo to poop itself which is why I was having issues with the player appearance menu earlier. I have since downloaded that mp-stub-clothes-patch thing from Alex106 over at GTA5Mods, added prefixes to all the file names to replace the original ones and streamed it as a resource.
> 
> I'm not sure if possible but perhaps Menyoo, vMenu, etc etc needs to ignore those files or perhaps servers need to stream them, same with the chameleon paints for it to take effect, though I'm not 100% certain.
> 
> _You'd have to rename the files yourself using Bulk Rename Utility (google it) if you wanted to do this)_

Ok I will try to see this.

**Comment by itsjustcurtis** [comment]
@TayMcKenzieNZ respectfully, please stop commenting if its not to provide a solution for the bug within menyoo. I understand you mean well, but I cannot fix this using third party software, so please stop suggesting it in issue comments.

@MixJesteR thanks for confirming, I wasn't sure it would, I have another fix to try and fix compatibility issues with older versions of the game. I'll ping you again when ready to test.

**Comment by MixJesteR** [comment]
> @TayMcKenzieNZ respectfully, please stop commenting if its not to provide a solution for the bug within menyoo. I understand you mean well, but I cannot fix this using third party software, so please stop suggesting it in issue comments.
> 
> @MixJesteR thanks for confirming, I wasn't sure it would, I have another fix to try and fix compatibility issues with older versions of the game. I'll ping you again when ready to test.

I guess the version you sent It worked. Didn't crash. I will test somethings that were useful to me, like spawning FEMALE MP Peds.

**Comment by MixJesteR** [comment]
> > @TayMcKenzieNZ respectfully, please stop commenting if its not to provide a solution for the bug within menyoo. I understand you mean well, but I cannot fix this using third party software, so please stop suggesting it in issue comments.
> > @MixJesteR thanks for confirming, I wasn't sure it would, I have another fix to try and fix compatibility issues with older versions of the game. I'll ping you again when ready to test.
> 
> I guess the version you sent It worked. Didn't crash. I will test somethings that were useful to me, like spawning FEMALE MP Peds.

OMG DIDN'T CRASH! SO GOOD! TY.

**Comment by itsjustcurtis** [comment]
Thank you for confirming, issue closed
