### ISSUE TITLE
Bike Chrome Wheels Not Present

### ISSUE THREAD

**Issue by GTMango** [itsjustcurtis/MenyooSP#28]
When the original Menyoo had it's Chrome Wheel options merged into one section, Chrome Bike Wheels were noticeably missing from this, and it looks like they still are. While not the biggest issue, there's no way to select Chrome Bike Wheels with Menyoo as it stands now. This also makes it impossible to select add-on bike wheels.

**Comment by itsjustcurtis** [comment]
Chrome wheels should still be visible if scrolling towards the bottom of the list. Like all other wheels the Bike wheel list is dynamically generated based on all content currently visible to the game.  

I will investigate, but I'm not sure I will be able to replicate.

**Comment by itsjustcurtis** [comment]
This should now be fixed, @GTMango please test the latest pre-release: https://github.com/itsjustcurtis/MenyooSP/releases/tag/v2.0.1a3

**Comment by GTMango** [comment]
Works like a charm now. Great stuff 👍🏿

![20240129000230_1](https://github.com/itsjustcurtis/MenyooSP/assets/141836327/b2ed8513-da20-4653-a061-57be3d8a0007)
![20240129000147_1](https://github.com/itsjustcurtis/MenyooSP/assets/141836327/bca0076c-7d98-440a-9f8a-a5ff623611d5)
![20240129000136_1](https://github.com/itsjustcurtis/MenyooSP/assets/141836327/a7163f05-ac74-4212-969b-c9613cae4e86)

**Comment by itsjustcurtis** [comment]
Awesome, glad to hear it
