### ISSUE TITLE
Please fix the makeup problem. They're all black and white for some reason.

### ISSUE THREAD

**Issue by Arronovsky** [itsjustcurtis/MenyooSP#29]
![GTA5 2024-01-28 12-46-43](https://github.com/itsjustcurtis/MenyooSP/assets/120739117/17110102-1a90-4aa7-95c6-3cfabffb940d)

**Comment by itsjustcurtis** [comment]
I don't fully understand how the makeup _should_ work. If you can elaborate on what you expect to see then I can investigate further.

**Comment by TayMcKenzieNZ** [comment]
Here's a database of how they're supposed to look. Hope this helps.

https://forge.plebmasters.de/decorations

**Comment by itsjustcurtis** [comment]
@TayMcKenzieNZ I didn't realise plebmasters had makeup as well. Thanks for sharing

**Comment by itsjustcurtis** [comment]
![image](https://github.com/itsjustcurtis/MenyooSP/assets/70447190/5cfcc67d-639d-4bd4-b714-c09985a2e22a)

Appears to be functioning correctly. The default state of makeup is un-painted, and the primary and secondary colours need to be changed.

**Comment by Arronovsky** [comment]
In past versions, you didn't have to choose a primary and secondary color in your makeup. Here is an example from the picture. This is the texture of the makeup itself. There are several colors, and in the game it will not look like in the picture, because of the fact that you need to overlay colors. You know what I mean?
![makeup](https://github.com/itsjustcurtis/MenyooSP/assets/120739117/1b3f8d0a-da0d-4992-9529-33c74f8301d3)

**Comment by Arronovsky** [comment]
In version 1.7.5 makeup works properly. I attach a link, you can see the source code and just paste it into your trainer.
https://github.com/MAFINS/MenyooSP/releases/tag/v1.7.5

**Comment by itsjustcurtis** [comment]
This is an intentional function added in commit 265 on the Mafins repo. The Feature is functioning as intended, reversing this change would remove the ability to select colour overlays.

**Comment by Arronovsky** [comment]
Is there any way to remove it?

**Comment by itsjustcurtis** [comment]
Only by regressing and reversing that change, which I do not intend to do. My objective is to improve and expand the functionality of Menyoo, not reduce it and undo the changes already made. If you have a suggestion on how this can be done without removing functionality, I am open to ideas.

**Comment by TayMcKenzieNZ** [comment]
Maybe if a makeup only has one set colour, then it defaults to that, but if
it has multiple colour options then allow them? So like say a makeup colour
is black by default, maybe Gray out the options?

**Comment by itsjustcurtis** [comment]
I'm currently investigating, from what I can tell the change was simply to tell the game that makeup can be colourable, there is _zero_ reference to which ones can or can't be painted. I'm trying to see if there is a way I can set the "default" look which can later be changed.

**Comment by Arronovsky** [comment]
Have you looked at how the makeups are arranged in the 1.7.5 version?

**Comment by Arronovsky** [comment]
Please understand, makeup is a very important thing to many people. And the old version of the trainer do not want to use at all.

**Comment by itsjustcurtis** [comment]
I have, all that has been done is turned the ability to change colour on or off, that is all. I am currently working on a compromise, as being able to colour the makeup is also important. Please have patience.

**Comment by Arronovsky** [comment]
Okay, well, thank you for your efforts ❤️

**Comment by Arronovsky** [comment]
Why is being able to change the color of your makeup important? Just in the same GTA Online such a function is not. It seems to always use the texture of the original makeup

**Comment by itsjustcurtis** [comment]
Because if it wasn't, then the original change would never have been made. Just because _you_ don't see it as important, doesn't mean others don't. I personally never use the ped stuff in menyoo, but I understand that you want to use it in a way different to me, so I am making it work.

**Comment by itsjustcurtis** [comment]
@Arronovsky please download the last pre-release (v2.0.1a4), this should fix your issue.

**Comment by Arronovsky** [comment]
@itsjustcurtis It's all working. Thank you so much! You are the best!
