### ISSUE TITLE
FiveM dying causes menyoo to stop working.

### ISSUE THREAD

**Issue by GLiTcH2** [itsjustcurtis/MenyooSP#35]
So I downloaded version v2.0.1a3 as that seemed to be the only version that would not crash when I joined my FiveM server which is on 3095 and everything is up to date. Anyways I noticed however a weird bug where Menyoo will work just fine but as soon as I die, I re-spawn and a few seconds later my character model is changed to Michael from story mode and then I am no longer able to open Menyoo at all. I need to leave the server and re-join to get it working again?

Edit - Never mind, I had to turn off the setting "Reset Player Upon Death (SP)" all good now!

**Comment by TayMcKenzieNZ** [comment]
There's a setting to keep your main character if I remember correctly but
yes, if you die, Menyoo won't open again

**Comment by TayMcKenzieNZ** [comment]
Ah sorry didn't see second half of your message lol
