### ISSUE TITLE
Bug with Ped Rotation after being attached

### ISSUE THREAD

**Issue by Eunice1191** [itsjustcurtis/MenyooSP#52]
Noticed that once a ped is attached to an object, the various rotation options in the attachment menu seem to get quite buggy. For example Yaw works, but Pitch does not. Doesn't seem to be an issue with objects though. Objects attached to other objects, rotate on all 3 axis as intended.

**Comment by itsjustcurtis** [comment]
I have a feeling this might be an intended function, or at least something from the game. Peds I _think_ are forced upright by the game, I'll have to see if some sort of native exists that forces then to rotate.

**Comment by itsjustcurtis** [comment]
Looking into the code, there is nothing inherently preventing a rotation from happening, and in testing in game, _certain_ inputs can demonstrate some level of rotation, which then resets when the game has caught up, telling me there is some sort of hard-coded piece that prevents a ped from being rotated away from vertical. Doesn't look like there is much that can be done about this unfortunately.

**Comment by Eunice1191** [comment]
Interestingly enough, if the ped is just Frozen in Place and not attached to anything, all 3 rotations work fine in manual placement options. However it's only during the attachment to an object and in the Attachment Options where only Yaw seems to work correctly.

**Comment by itsjustcurtis** [comment]
Oh that is interesting, I wonder if forcing something frozen would allow it to still be attached?

**Comment by Eunice1191** [comment]
Yeah I tried both but it doesn't seem to matter if the ped is frozen or not during attachment, still the same result
