### ISSUE TITLE
[SUGGESTION] Boat Anchor

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [itsjustcurtis/MenyooSP#55]
I think it would be a really neat idea to add an anchoring system with blips; it would give the ability to anchor boats, jetskis, seaplanes, submersibles and amphibious helicopters to keep them in place and based on what type of vehicle it is, it would be given a blip on the map.

The way it could work is, a message prompt on the screen tells you to press a keybind to anchor the vehicle. The player would have to be in the driver's seat to anchor or remove the anchor.

The vehicle will respond to the ocean's waves etc, however it won't drift off. Submersibles can be anchored any depth *(besides the obvious crush depth)*

Perhaps press ‘e’ (by default) to deploy an anchor in a boat and the same key to raise the anchor. Anchor can not be deployed on land or very shallow water, also can’t be deployed while the boat is moving over a configurable speed. *(An ini file could probably be beneficial in this regards?)*

If you need inspiration, there's a C++ script for FiveM that's open source you can look at here:

https://github.com/PsychoDad9999/GTA5-Mods/tree/master/AdvancedAnchor

I hope you consider something like this in a future release 🙂

**Comment by itsjustcurtis** [comment]
Latest alpha build includes this, please test that its functioning correctly. Option exists in vehicle options

**Comment by TayMcKenzieNZ** [comment]
@itsjustcurtis I have tested this and it works 99% perfect. I think what should happen is that when the Anchor Boat option is toggled, the boat engine is disabled also, as I'm able to sit in the boat and drive, and it will move a few inches before the anchor option is kicked back in, to stop this, the engine could be disabled. However in saying that, there is also an option 'Kill Engine' and 'Keep Engine & Lights On', these options may conflict.

**Comment by TayMcKenzieNZ** [comment]
Fly Mode is also able to bypass the anchor

**Comment by itsjustcurtis** [comment]
I would expect both of these side effect to be honest, trying to rectify would likely cause the game to get confused. Fly mode bypasses all vehicle controls and instead manipulates the object position directly so allowing anchor to stop that would break a lot of stuff. I'm gonna close this as resolved given both of these "issues" are more inherent functions

**Comment by TayMcKenzieNZ** [comment]
No problem. How do you feel about disabling the engine when the anchor is enabled?

**Comment by itsjustcurtis** [comment]
Same sort of story, I imagine there will be some conflict between the two commands, and I'd rather not _force_ functions on users; if they want the engine disabled, they can turn it off via the other options.

**Comment by TayMcKenzieNZ** [comment]
That's fair, thanks for adding the anchor toggle anyways 😊
