### ISSUE TITLE
DLC Vehicles despawning in latest version of the game

### ISSUE THREAD

**Issue by itsjustcurtis** [itsjustcurtis/MenyooSP#6]
Memory flags to prevent dlc vehicles despawning are either out-dated or incorrect for b3095.

**Comment by SkyK0T** [comment]
Need to update the native, on this site 

https://alloc8or.re/gta5/nativedb/
or
https://nativedb.dotindustries.dev
https://gta5.nativedb.dotindustries.dev/natives

you can generate and tweak a bit? I also attach my file, it is not new but from 11/29/2023 but at least it is ready, but it is better to update everything to version 3095.
[Natives.zip](https://github.com/itsjustcurtis/MenyooSP/files/13998114/Natives.zip)
, but it is better to update everything to version 3095.

**Comment by SkyK0T** [comment]
I think you need to download, and replace each line with a blank space for those lines	NATIVE_DECL 
and adjust the spaces and _ to compile normal

**Comment by itsjustcurtis** [comment]
> Need to update the native, on this site
> 
> https://alloc8or.re/gta5/nativedb/ or https://nativedb.dotindustries.dev https://gta5.nativedb.dotindustries.dev/natives
> 
> you can generate and tweak a bit? I also attach my file, it is not new but from 11/29/2023 but at least it is ready, but it is better to update everything to version 3095. [Natives.zip](https://github.com/itsjustcurtis/MenyooSP/files/13998114/Natives.zip)

DLC Vehicle despawning is done via memory edits, not native functions. 

As it turns out, the memory pointers are unchanged since b2802 and the function there works fine in the current version of the game.

**Comment by SkyK0T** [comment]
Well, it is still better to update to the current version of the game, in order to avoid further problems))) will not be superfluous for sure

**Comment by SkyK0T** [comment]
update GTAmemory.cpp 
float GeneralGlobalHax::GetPlayerHeight()
{
	auto baddr = *GeneralGlobalHax::WorldPtrPtr();
	if (baddr)
	{
		auto gameVersion = GTAmemory::GetGameVersion();
		if (gameVersion <= eGameVersion::VER_1_0_3095_0) //2802 2944
			return *(GetMultilayerPointer<float*>(baddr, std::vector<DWORD>{0x8, 0x88}));
	}
	return 1.0f;
}
void GeneralGlobalHax::SetPlayerHeight(float value)
{
	auto baddr = *GeneralGlobalHax::WorldPtrPtr();
	if (baddr)
	{
		auto gameVersion = GTAmemory::GetGameVersion();
		if (gameVersion <= eGameVersion::VER_1_0_3095_0) //2802 2944
			*(GetMultilayerPointer<float*>(baddr, std::vector<DWORD>{0x8, 0x88})) = value;
	}
}

and 
	case eGameVersion::VER_1_0_3095_0: default:
	*GTAmemory::GetGlobalPtr<INT32>(4541411) = uSure ? 1 : 0; break;
	*GTAmemory::GetGlobalPtr<INT32>(4540731) = uSure ? 1 : 0; break;
	*GTAmemory::GetGlobalPtr<INT32>(4540726) = uSure ? 1 : 0; break; //vh bypass globalHandle(4540726).As<int>() = 1;
	*GTAmemory::GetGlobalPtr<INT32>(1669394) = uSure ? 1 : 0; break; //bypass_game globalHandle(1669394).As<int>() = 1;
	*GTAmemory::GetGlobalPtr<INT32>(2697019) = uSure ? 1 : 0; break; //freemode_bypass Model Spawn

**Comment by SkyK0T** [comment]
GetPlayerMovementSpeed not work I don't know if the addresses have changed, I can't find the new ones if they have.

**Comment by itsjustcurtis** [comment]
>update GTAmemory.cpp
float GeneralGlobalHax::GetPlayerHeight()
{
auto baddr = *GeneralGlobalHax::WorldPtrPtr();
if (baddr)
{
auto gameVersion = GTAmemory::GetGameVersion();
if (gameVersion <= eGameVersion::VER_1_0_3095_0) //2802 2944
return (GetMultilayerPointer<float>(baddr, std::vector{0x8, 0x88}));
}
return 1.0f;
}
void GeneralGlobalHax::SetPlayerHeight(float value)
{
auto baddr = *GeneralGlobalHax::WorldPtrPtr();
if (baddr)
{
auto gameVersion = GTAmemory::GetGameVersion();
if (gameVersion <= eGameVersion::VER_1_0_3095_0) //2802 2944
(GetMultilayerPointer<float>(baddr, std::vector{0x8, 0x88})) = value;
}
}
>
>and
case eGameVersion::VER_1_0_3095_0: default:
*GTAmemory::GetGlobalPtr(4541411) = uSure ? 1 : 0; break;
*GTAmemory::GetGlobalPtr(4540731) = uSure ? 1 : 0; break;
*GTAmemory::GetGlobalPtr(4540726) = uSure ? 1 : 0; break; //vh bypass globalHandle(4540726).As() = 1;
*GTAmemory::GetGlobalPtr(1669394) = uSure ? 1 : 0; break; //bypass_game globalHandle(1669394).As() = 1;
*GTAmemory::GetGlobalPtr(2697019) = uSure ? 1 : 0; break; //freemode_bypass Model Spawn

>GetPlayerMovementSpeed not work I don't know if the addresses have changed, I can't find the new ones if they have.

It has already been updated to the current game version. I'm not sure why you're talking about player movement speed as that has nothing to do with this issue. 

If you want to make edits, please do so via the proper means; fork this repository, make the relevant changes, then send a pull request.

**Comment by itsjustcurtis** [comment]
Unable to be tested as new natives are incompatible with old versions of the game.

**Comment by itsjustcurtis** [comment]
Fix does not appear to work for some users, further investigation required.

**Comment by itsjustcurtis** [comment]
Its seems that some users games are using the new 4541411 pointer, and some have retained the older 4540726. No pattern found as yet, may be easiest to set both flags to true.

**Comment by itsjustcurtis** [comment]
@katsutosh we may need to get clever with this, looks like this breaks something in Fivem. Going to see if I can create a bypass as the function isn't really needed for fivem
