### ISSUE TITLE
[Bug] Menyoo does not prevent you from attaching an entity to another entity that is already attached to it and crashing itself

### ISSUE THREAD

**Issue by WithLithum** [itsjustcurtis/MenyooSP#60]
### Expected Behaviour

You will be unable to attach an object to an object that is already attached _to_ it.

### Actual Behaviour

Menyoo allows this invalid attaching operation, causing the game to raise an exception and crashes the trainer. ScriptHookV terminates the trainer, and while the game still runs, the trainer have indeed been terminated.

### Reproduction

To reproduce this issue follow the steps below: 

1. Create two entites (props, objects, vehicles etc.) we call entities A and B.
2. Attach entity A to entity B using Spooner
3. Try attaching entity B to entity A. ScriptHookV shows a message indicating that Menyoo have caused an exception, and have been terminated. Tab-back into the game and you will see that Menyoo have indeed stopped working.

**Comment by itsjustcurtis** [comment]
Thanks for flagging, this should be a relatively straightforward one to sort, I imagine its just a case of checking whether they're already attached
