### ISSUE TITLE
DLC vehicles are despawning in b3095

### ISSUE THREAD

**Issue by katsutosh** [itsjustcurtis/MenyooSP#7]
after the change in commit https://github.com/itsjustcurtis/MenyooSP/commit/259aa9687013ef8e77536d362bfb5cdaef955978 dlc vehicles are despawning in b3095
before this commit it's works fine

**Comment by itsjustcurtis** [comment]
This is really odd, the vehicles were despawning in SP until I made that change.

**Comment by itsjustcurtis** [comment]
Duplicate of #6 - Re-opening for history and closing this
