### ISSUE TITLE
FiveM hangs in black screen with Menyoo 2.0.2 

### ISSUE THREAD

**Issue by mcdim** [itsjustcurtis/MenyooSP#71]
Hi,
GTA5 ver. 3095, FiveM (b2600 beta) starts in Story Mode fine. When Menyo 2.0.2 is installed in FiveM (ASI file - in "plugins" folder, "menyooStaff "- in "subprocesses" folder) it makes FiveM hang indefinitely in black screen.
What can be wrong, please?
Thank you!

**Comment by itsjustcurtis** [comment]
That is an incredibly out-dated version of FiveM. Attempts have been made to fix a number of backwards compatibility options, but GTA has added several natives to the game that will not be recognised by builds that old

**Comment by mcdim** [comment]
My apologies, not "b2600" - it is "b2699".
On startup FiveM says "ver. 7545" (at the bottom right), when starting game in story mode - it says "FiveM (b2699)" (at top right).

**Comment by itsjustcurtis** [comment]
My answer does not change, this is still 4 versions out of date.

**Comment by TayMcKenzieNZ** [comment]
I use Menyoo on FiveM 3095 without any issues and have used it on older
gamebuilds with no issues either, as the ASI supports them all. However you
mentioned FiveM single player. Barely anyone plays that. It's either normal
SP or normal FiveM server.

**Comment by mcdim** [comment]
@itsjustcurtis: Thank you for coming back. I downloaded FiveM client directly from "FiveM.net", not sure how to move it to 3095 (my game is actually 3095!).
@TayMcKenzieNZ: Thank you for reply. Do you mean people use FiveM server on their local computer? Or they play online on servers which already have Menyoo installed?

**Comment by TayMcKenzieNZ** [comment]
Both. And you have to enforce your gamebuild. Quick google search will show
you how.

**Comment by mcdim** [comment]
Thanks again!
