### ISSUE TITLE
Controll issues?

### ISSUE THREAD

**Issue by KingOreoTheThird** [itsjustcurtis/MenyooSP#78]
I cant use back button in menus I've looked at the old post where controls are posted and it says backspace is the button for that am I wrong?

**Comment by david2hu** [comment]
It's either backspace or Num 0. But I haven't tried it on Menyoo 2.

**Comment by itsjustcurtis** [comment]
unable to replicate issue, backspace and numkey 0 are the defaults for keyboard, b on a controller, but these can be changed in the .ini.
