### ISSUE TITLE
Why can't I do tasks after replacing the protagonist's model?

### ISSUE THREAD

**Issue by KobatoKK** [itsjustcurtis/MenyooSP#80]
Why can't I do tasks after replacing the protagonist's model? Special abilities cannot be used either. I can't get into the house either.

**Comment by itsjustcurtis** [comment]
I'm not sure what the issue is here, can you go into more detail please? If it is only that protag houses or special abilities cannot be used after changing the ped model, this is part of the game; Players can only access protag abilities and properties when using that character.

**Comment by itsjustcurtis** [comment]
No response after 3 months. Closing
