### ISSUE TITLE
Character Stat Edits Not Saving

### ISSUE THREAD

**Issue by Sam-Man16** [itsjustcurtis/MenyooSP#81]
Trying to change the character stats either immediately has them revert back to their original values or has no effect when you edit one of the characters you aren't playing as. The only stat that seems to work when edited is the special ability stat. Running on latest game and mod version.

**Comment by itsjustcurtis** [comment]
I have a feeling that stat edits mayyy be direct memory edits, which get out-dated with every game version. If that is the case this may not be easily repairable.

**Comment by itsjustcurtis** [comment]
related to #59, closing as duplicate
