### ISSUE TITLE
Error menyoo

### ISSUE THREAD

**Issue by Leeroy736** [itsjustcurtis/MenyooSP#82]
When scrolling through women's clothing, this error occurs. This is not the case with men's Freemode.
![Снимок экрана 2024-04-09 151953](https://github.com/itsjustcurtis/MenyooSP/assets/76574035/95f3f7e5-6b98-4be1-9857-aaa764bd2307)

**Comment by itsjustcurtis** [comment]
Are you able to repeat the error reliably? Is it a specific item of clothing that the error occurs on? If you can provide more detail to help me replicate that would be useful.

**Comment by itsjustcurtis** [comment]
No further information provided, closing
