### ISSUE TITLE
Menyoo - Not working

### ISSUE THREAD

**Issue by lumberingtime** [itsjustcurtis/MenyooSP#83]
As of right now, Menyoo isn't updated to the most recent GTA 5 version, **_is this going to be fixed soon_**, or will this be broken for a while?

**Comment by itsjustcurtis** [comment]
Scripthook has not yet been updated. Until it has we cannot say that Menyoo is not working for the latest version. According to the changelog, minimal changes have occurred so there should be no reason that it has broken anything in Menyoo.

**Comment by lumberingtime** [comment]
I'll test it out with the new script hook.

**Comment by lumberingtime** [comment]
Good news, it works!
