### ISSUE TITLE
[Suggestion] FiveM Open Menu Key ⚙️

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [itsjustcurtis/MenyooSP#88]
In FiveM, pressing F8 opens the console. This conflicts with Menyoo.

What I suggest for people, is that they change it to the `~` key which, depending on your keyboard layout, should be before the 1, unless you have some crappy cheap keyboard. This is `open_key = 192`.

**Comment by itsjustcurtis** [comment]
I appreciate this isn't an issue and wont close it, but I'm unsure that this is the best medium to share this info with users. I might update the readme with the suggestion

**Comment by TayMcKenzieNZ** [comment]
Fair call 😀
