### ISSUE TITLE
Vehicle Spawn list Empty in Fivem

### ISSUE THREAD

**Issue by itsjustcurtis** [itsjustcurtis/MenyooSP#9]
![image](https://github.com/itsjustcurtis/MenyooSP/assets/70447190/01ddc848-b756-4e86-a5ff-054187fb34d5)

Believed related to the vehiclelist.xml being removed. v2.0.0a1 (prior to removal) confirmed working okay

**Comment by metoxys** [comment]
Can always reopen #4

**Comment by itsjustcurtis** [comment]
> Can always reopen #4

That might be the best immediate solution

**Comment by katsutosh** [comment]
i think, i found the issue - will check it deeper and make a PR for a fix
it has something to do with the native `IS_VEHICLE_GEN9_EXCLUSIVE_MODEL` because in FiveM with version b3095 it works

**Comment by itsjustcurtis** [comment]
PR #10 confirmed fix
