### ISSUE TITLE
Just a little thing

### ISSUE THREAD

**Issue by david2hu** [itsjustcurtis/MenyooSP#98]
I've already did a suggestions list some months ago, but I forgot to mention one very important thing:

Adding hotkeys to certain abilities, for example for Super Jump, Super Run, Fly mode, Smash Ability, Force field, etc. (almost every feature you can find on the Player Options menu).
Also some hotkeys for Vehicle Options would be useful as well, like Vehicle Jump, SuprKar mode, Race Boost on Horn, Fly...
I thought these hotkeys would be customizable in the .ini file, which would be great! :)

If this suggestion was mentioned before, sorry. Thanks anyway!

**Comment by itsjustcurtis** [comment]
See comments in #18
